AUTHOR:
  jz-rolling  

SYSTEM:
  VERBOSE: FALSE

EMAIL:
  jzrolling@outlook.com

FEATURE:
  SIGMAS: [0.3,0.8,1.5,3,5]
  NUM_WORKERS: 12
  ROG: True
  RIDGE: True
  SOBEL: True
  SHAPEINDEX: True
  SELEM: [1,'square',5]
  
IMAGE:
  EDGE: 0.2
  ROG_SIGMAS: [0.5,10]
  
SEGMENTATION:
  SHAPEINDEX:
    SHAPEINDEX_SIGMA: 1
    SHAPEINDEX_LOW: 25
    SHAPEINDEX_HIGH: 85
    MIN_SEED_SIZE: 50
  MASK:
    METHOD: 1